@URLBASE = http://localhost:3000

### Criar pessoa
POST {{URLBASE}}/users
Content-Type: application/json

{
  "name": "Ana",
  "email": "ana@uol.com.br",
  "login": "ana",
  "password": "1234",
  "birth": "2000-05-05",
  "type": "admin"
}

### Obter todos os usuários
GET {{URLBASE}}/users