@base_address = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjQ4NzQ4MTgwLCJleHAiOjE2NDg4MzQ1ODB9.Q0FrAZQpPhltvgc7FxsSMJtncDTkJAKGNBvOTuvkRH0


GET {{base_address}}/todo HTTP/1.1


###

GET {{base_address}}/todo/7 HTTP/1.1

###

POST {{base_address}}/todo HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "title": "Reunião",
    "description": "asd",
    "date": "2022-03-31T11:38:00",
    "done": false
}

###

PUT {{base_address}}/users/1 HTTP/1.1
Content-Type: application/json

{
    "name": "Carlos",
    "email": "carlos@utfpr.edu.br",
    "login": "carlos",
    "password": "1234"
}

###

DELETE {{base_address}}/todo/1 HTTP/1.1
Content-Type: application/json